version: '3.8'

services:
  app_blue:
    image: yimikaade/wonderful:devops-stage-two
    environment:
      - RELEASE_ID=blue-v1
      - PORT=3000
      - APP_POOL=blue
    ports:
      - "8081:3000"
    networks:
      - bg-net

  app_green:
    image: yimikaade/wonderful:devops-stage-two
    environment:
      - RELEASE_ID=green-v1
      - PORT=3000
      - APP_POOL=green
    ports:
      - "8082:3000"
    networks:
      - bg-net

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    depends_on:
      - app_blue
      - app_green
    networks:
      - bg-net


networks:
  bg-net:
    driver: bridge
